Fix #113: Refactor getSitePackagesPath to use python discovery
jfrog/build-info-go pull request #114
Opened 2022-10-24 06:32 UTC by rvodden

- [X] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [X] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [X] This pull request is on the dev branch.
- [X] I used gofmt for formatting the code before submitting the pull request.
-----

2022-10-24 06:34 UTC, rvodden commented
I have read the CLA Document and I hereby sign the CLA

2022-10-24 08:51 UTC, talarian1 commented
Hi @rvodden, thanks a lot for your contribution.
I suggest we will wait with those changes, as for Poetry 1.2 and above the file 'direct_url.json' is not created anymore.
You can see this [discussion](https://github.com/orgs/python-poetry/discussions/6869) for more details.
The only usage for the getSitePackagesPath logic is getting those files. 
Sorry for the inconvenience and thanks again!

2022-10-24 09:13 UTC, talarian1 requested changes

2022-10-24 09:13 UTC, talarian1 commented on utils/pythonutils/poetryutils.go
> +	siteCmd := utils.NewCommand("poetry", "run", []string{"python", "-c", "import sysconfig;  print(sysconfig.get_paths()['purelib']])"})
```suggestion
	siteCmd := utils.NewCommand("poetry", "run", []string{"python", "-c", "import sysconfig;  print(sysconfig.get_paths()['purelib'])"})
```

2022-10-24 09:47 UTC, rvodden commented
> Hi @rvodden, thanks a lot for your contribution.
> I suggest we will wait with those changes, as for Poetry 1.2 and above the file 'direct_url.json' is not created anymore.
> You can see this [discussion](https://github.com/orgs/python-poetry/discussions/6869) for more details.
> The only usage for the getSitePackagesPath logic is getting those files.
> Sorry for the inconvenience and thanks again!

aha great! I must admit i was thinking of authoring a poetry plugin which would output buildinfo... would that be interesting as an alternative to having to install jf-cli ?

2023-02-07 07:50 UTC, talarian1 commented
Thanks again for your interest in this, and for your effort.
I'm closing this for now, as we discussed [here](https://github.com/orgs/python-poetry/discussions/6869) we will need a new implementation to solve this issue.

2023-02-07 07:50 UTC, closed without merging