Pipelines build-info-go release
jfrog/build-info-go pull request #15
Opened 2021-11-18 12:24 UTC by gailazar300

- [x] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
Build and release build-info-go cli binaries.

2021-11-20 14:10 UTC, yahavi requested changes

2021-11-20 14:10 UTC, yahavi commented on pipelines.yml
> +    gitProvider: il_automation
```suggestion
  - name: buildinfoGoGit
    type: GitRepo
    configuration:
      path: jfrog/build-info-go
      branches:
        include: main
      gitProvider: il_automation
```

2021-11-20 14:10 UTC, yahavi commented on pipelines.yml
> +              trigger : false
```suggestion
              trigger: false
```

2021-11-20 14:10 UTC, yahavi commented on release/build.sh
> +# Keep 'linux-386' first to prevent unnecessary uploads in case the built version doesn't match the provided one.
What's special in linux-386? I couldn't understand the reason

2021-11-24 09:46 UTC, eyalbe4 requested changes
Let's also modify the binaries release logic, to avoid deployment failures, as a result of the new binaries overriding the old ones.

2021-12-01 09:41 UTC, closed without merging