Add support to calculate npm tree only by package-lock.json file
jfrog/build-info-go pull request #194
Opened 2023-09-12 21:30 UTC by asafambar

- [ ] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-09-12 21:34 UTC, asafambar commented
This PR introduce more control on the possible ways npm tree is calculated:
1) create the tree (which is the "ls" command) only b the package-lock file, with no mater if noe modules exists.
2) if package-lock exists, check if the package.json is more updated than the lock, if so, then recalculate th package-lock file.

2023-09-20 12:45 UTC, yahavi requested changes

2023-09-20 12:45 UTC, yahavi commented on build/utils/npm_test.go
> +	require.NoError(t, os.WriteFile(filepath.Join(path, "package-lock.json"), data, info.Mode().Perm()))
Can be one lined:
```suggestion
	assert.NoError(t, utils.MoveFile(filepath.Join(path, "package-lock_test.json"), filepath.Join(path, "package-lock.json")))
```

2023-09-20 12:45 UTC, yahavi commented on build/utils/npm_test.go
> +	require.NoError(t, os.Chtimes(filepath.Join(path, "package.json"), time.Now(), time.Now()))
Can be without sleep
```suggestion
	require.NoError(t, os.Chtimes(filepath.Join(path, "package.json"), time.Now(), time.Now().Add(time.Millisecond * 20)))
```

2023-09-20 12:45 UTC, yahavi commented on build/utils/npm_test.go
> +	}
For better test readability, is it possible to export this to a const outside of the test method?

2023-10-01 11:40 UTC, yahavi approved these changes

2023-10-03 09:45 UTC, merged