Add UTF-16 encoding to Xml Unmarshall
jfrog/build-info-go pull request #231
Opened 2024-02-04 11:11 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2024-02-05 15:11 UTC, fourpastmidnight commented on build/utils/dotnet/dependencies/packagesconfig.go
> +		// Failed while trying to parse xml file. Nuspec file could be an utf-16 encoded file.
Yes! This is the issue I was running into. Now I see why the original fix didn't work.

2024-02-13 14:35 UTC, fourpastmidnight commented
What's going on with this PR, as I haven't seen any movement on this for about 2 weeks? I'm looking for this fix, as I'm gearing up to go to production soon and would like to know if I'll be able to use the JFrog Restore task in my build pipelines.

2024-02-16 16:12 UTC, yahavi requested changes

2024-02-16 16:12 UTC, yahavi commented on build/utils/dotnet/dependencies/packagesconfig.go
> +		utf16BOM := "\uFEFF"
Let's make it a file const

2024-02-16 16:12 UTC, yahavi commented on build/utils/dotnet/dependencies/packagesconfig.go
> +		err = xml.Unmarshal([]byte(stringXml), obj)
Let's add checkerr

2024-02-16 16:12 UTC, yahavi commented on build/utils/dotnet/dependencies/packagesconfig.go
> +		// Failed while trying to parse xml file. Nuspec file could be an utf-16 encoded file.
Let's add a debug log message here to mention that we are using this fallback

2024-02-18 09:41 UTC, sverdlov93 commented on build/utils/dotnet/dependencies/packagesconfig.go
> +		err = xml.Unmarshal([]byte(stringXml), obj)
@yahavi its build-info-go, no check error here

2024-02-18 09:51 UTC, merged

2024-03-01 18:55 UTC, fourpastmidnight commented
Awesome, glad to see this has been completed. Has this been formally released?

2024-03-13 16:35 UTC, fourpastmidnight commented
Did you guys actually test that this works with the package mentioned in issues #464 and #475? I'm _still_ getting an error trying to use the JFrog task to restore `microsoft.web.infrastructure-1.0.0`.