fix: same vcs info appened twice when running jf rt build-add-git command twice
jfrog/build-info-go pull request #250
Opened 2024-04-19 09:38 UTC by gerrnot

- [x] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2024-04-19 11:12 UTC, eyalbe4 requested changes
Thanks for this PR @gerrnot.
Please review the checks failures.

2024-04-19 11:37 UTC, gerrnot commented
@eyalbe4 Thanks! I found evidence that this whould be fixed by a go upgrade, so I merged to already approved (at least partly) sibling PR: https://github.com/jfrog/build-info-go/pull/249

2024-05-29 11:38 UTC, EyalDelarea commented
Hey @gerrnot 

We've just update to go 1.22.3,
Can you confirm that the issue is resolved by updating the go version?

2024-06-03 16:28 UTC, gerrnot commented
I have read the CLA Document and I hereby sign the CLA

2024-06-03 18:32 UTC, gerrnot commented
@EyalDelarea Thanks, yes, the build was green after that. I rebased.

2025-01-07 08:43 UTC, EyalDelarea commented
Hey @gerrnot 

I'm closing this PR, feel free to reopen the pull request if needed.

2025-01-07 08:43 UTC, closed without merging