Add poetry support
jfrog/build-info-go pull request #91
Opened 2022-07-21 14:42 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-07-24 08:46 UTC, sverdlov93 commented on utils/pythonutils/poetryutils.go
> +// Executes the poetry-dependency-map script and returns a dependency map of all the installed poetry packages in the current environment to and another list of the top level dependencies
```suggestion
// Executes the poetry-dependency-map script and returns a dependency map of all the installed poetry packages in the current environment and another list of the top level dependencies
```

2022-07-24 09:24 UTC, sverdlov93 commented on utils/pythonutils/poetryutils.go
> +// Returns the key array of a given map
```suggestion
// Returns the key array of a given map. (Should be replaced by maps.keys() when we move to go 1.18)
```

2022-07-24 09:24 UTC, sverdlov93 commented on utils/pythonutils/poetryutils.go
> +// Get the project-name by parse the pyproject.tomal file
```suggestion
// Get the project-name by parse the pyproject.toml file
```

2022-07-24 09:24 UTC, sverdlov93 commented on build/python.go
>  		pm.containingBuild.logger.Debug("Couldn't retrieve the package name from Setup.py. Reason: ", pkgNameErr.Error())
Should change the error string (setup.py)

2022-09-11 09:57 UTC, eyalbe4 requested changes

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/poetryutils.go
> +// Executes the poetry-dependency-map script and returns a dependency map of all the installed poetry packages in the current environment and another list of the top level dependencies
Let's better describe the structure of the returned values. Maybe add an examples to help the reader understand the structure.

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/poetryutils.go
> +		return "", nil, err
It may be safer to return an empty array instead of nil.
The sane goes for the below return statement.

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/poetryutils.go
> +// Get the project-name by parse the pyproject.toml file
parse --> parsing

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/poetryutils.go
> +// Get the project-name by parse the poetry.lock file
parse --> parsing

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/poetryutils.go
> +// (TODO - Should be replaced by maps.keys() when we move to go 1.18)
Let's impelent this TODO, beucase I think we're alerady using go 1.18.

2022-09-11 09:57 UTC, eyalbe4 commented on utils/pythonutils/utils.go
> +	}
The above can be simplified to -
```
if err != nil || !validPath {
    return "", err
}
```

2022-09-13 16:58 UTC, merged